services:
  discord-trello-bot:
    build: .
    container_name: discord-trello-bot
    restart: unless-stopped
    init: true  # Enable proper signal handling
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Mount logs directory (create if doesn't exist)
      - ./logs:/app/logs
      # Read-only temporary filesystem for security
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 32M
    networks:
      - bot-network
    # Resource limits (optimized for Discord bot)
    mem_limit: 128m
    cpus: 0.2
    # Security enhancements
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"  # Non-root user
    # Enhanced health check
    healthcheck:
      test: [
        "CMD", 
        "node", 
        "-e", 
        "const { Client } = require('discord.js'); const client = new Client({ intents: [] }); client.ws.status === 0 ? process.exit(0) : process.exit(1);"
      ]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 30s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
    # Metadata labels
    labels:
      - "app.name=discord-trello-bot"
      - "app.version=1.0.0"
      - "app.description=Discord bot that creates Trello cards"
      - "maintainer=user"
      - "environment=production"

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
    driver: local